language: python
python:
  - 3.6
before_script:
  - pip install .
script: python -m pytest
after_script:
  - pip install coveralls
  - coverage run --source=salty setup.py test
  - coveralls
branches:
  only:
    - master
deploy:
  provider: pypi
  user: markcial
  password:
    secure: liMmLPxnNCWc54E5u3f29xAkVBoXHv5s7vM88bFeOn3aUXzofyX0EgXyfcGanDD+YF3hHkbiPQbyqSDkg+flphVx0/ynyd0BUNn7zlX8i9uskZHX28nMbOea2y07O7UGfuYitsqFGCD2TaYGiobOTrb9xjFthBuS5YDHlEu3vs90yIGDTkdJaIWPwysphYl7luYHVcVF1VHAv/mwCTid7SvVEHJ7lBmJNoo9YtcKFek1jtZe17ogzeyy4Owa2f0VKu03SgH1qjUPYqSTIo4c9RaRknlSTFnxfOJn2FkhusKAUCbcLc4qpGK3W4DBEhKtez+oecxwTeYLQUlPwKYQwOfvMHuAhUbVd90b6IXuHBijWC/apSTR1RD7F3wDC7jYfhxX4agrXlkmXq+2QaJA1SC8Wi7AqdvD/GzcKTG5WfmH3yYWsEmEyjoHFEnCbE7qkwN26GAH+rKlhwig+t10vq6KGVkVjfzKsPOg1B8IUVHk17nXg/+vU3yLygIYLpPxII9/xyap9gbcvwKnKYf+FSmQQRKjYokwRBmg3kVfVyV3e8StsC+H6d7FEizxWuTd3glGz3rd0+9KJOk495wJrzWxnlMMbmX5niIgpkThA53mFJ3BkQ1L1lopHQrweDyoGZBQFhtuZ+1Awn3qdYcYPeSfJ2fzhj3YkLhERV0oUeE=
